# Generated by Django 5.1.4 on 2025-03-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpcoding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='execution_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='output',
            field=models.TextField(blank=True),
        ),
    ]
