# Generated by Django 5.1.4 on 2025-03-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpcoding', '0004_battle_player1_results_battle_player2_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='function_name',
            field=models.CharField(default='solve', max_length=100),
        ),
    ]
