# Generated by Django 5.1.4 on 2025-03-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpcoding', '0005_codingquestion_function_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='function_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
