# Generated by Django 5.0.7 on 2025-03-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='instructor_resumes/'),
        ),
    ]
